In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

## Exploratory Data Analysis
`An approach of analyzing data sets to summarize their main characteristics`


## A Basic EDA Workflow
1. Load and Inspect the Data
>Get the data and observe its features, labels, and datatypes

3. Clean the Data

>Handle missing values, duplicates, and outliers

3. Univariate Analysis

>Analyze one variable at a time

4. Bivariate Analysis

>Analyze two variables at a time

5. Multivariate Analysis

>Analyze three or more variables at a time

In [2]:
import pandas as pd 
import numpy as np

In [3]:
train = pd.read_csv("https://raw.githubusercontent.com/piush-ml/review-sentiment-analysis-dataset/refs/heads/main/data/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/piush-ml/review-sentiment-analysis-dataset/refs/heads/main/data/test.csv")

In [4]:
train.head()

,id,review_date,title,review_text,product_category,user_country,verified_purchase,price,discount,rating,helpful_votes,total_votes,sentiment
0,0,2022-01-31,NaN,VERY BAD QUALITY AND DISAPPOINTING EXPERIENCE....,Home,UK,True,69.44,0.30,2,5,6,negative
1,1,2022-12-30,Bad Purchase,Excellent performance and great value. Rating:...,Books,UK,True,40.69,0.49,3,3,6,neutral
2,2,2021-05-10,Best Buy,Very bad quality and disappointing experience....,Books,Australia,True,40.52,0.38,4,1,5,positive
3,3,2022-07-18,Okay Item,Very bad quality and disappointing experi...,Electronics,Australia,True,41.96,0.25,3,9,16,neutral
4,4,2022-02-04,NaN,THIS PRODUCT IS AMAZING AND WORKS PERFECTLY. R...,Clothing,Canada,False,93.21,0.12,5,6,11,positive

In [5]:
test.head()

,id,review_date,title,review_text,product_category,user_country,verified_purchase,price,discount,rating,helpful_votes,total_votes
0,20000,2022-07-21,Okay Item,EXCELLENT PERFORMANCE AND GREAT VALUE. RATING:...,Toys,Canada,True,47.20,0.16,2,4,6
1,20001,2021-01-15,Great Product,Very bad quality and disappointing experi...,Home,India,True,18.17,0.23,2,5,10
2,20002,2023-03-12,Bad Purchase,Highly recommend this product. Rating: 4/5!!!,Books,USA,True,72.99,0.32,4,5,13
3,20003,2021-12-08,Okay Item,"Terrible build quality, broke quickly. Rating:...",Beauty,NaN,True,65.60,0.34,4,4,11
4,20004,2021-12-10,Worth It,Very bad quality and disappointing experience....,Electronics,UK,False,51.86,0.05,4,5,11